# Generated by ocis init
{ config, ... }:
let
  ph = config.sops.placeholder;

  service_account_secret = ph."ocis/service_account_secret";

  admin_password = ph."ocis/admin_password";
  idm_password = ph."ocis/idm_password";
  reva_password = ph."ocis/reva_password";
  idp_password = ph."ocis/idp_password";
in {
  utils.ocis.ocis = {
    token_manager.jwt_secret = ph."ocis/jwt_secret";
    machine_auth_api_key = ph."ocis/machine_auth_api_key";
    system_user_api_key = ph."ocis/system_user_api_key";
    transfer_secret = ph."ocis/transfer_secret";
    system_user_id = "a8ebfa7a-c5bf-4f4e-8249-c281b22c9bb5";
    admin_user_id = "783f5525-7b62-4f80-b18f-68992dfca5b6";
    graph = {
      application.id = "092ae09e-49b8-4fd9-9467-fea39aef5fec";
      events.tls_insecure = false;
      spaces.insecure = false;
      identity.ldap.bind_password = idm_password;
      service_account = {
        service_account_id = "3b63d997-a7c8-4315-a2f4-d9b5792f79d9";
        inherit service_account_secret;
      };
    };
    idp.ldap.bind_password = idp_password;
    idm.service_user_passwords = {
      inherit admin_password;
      inherit idm_password;
      inherit reva_password;
      inherit idp_password;
    };
    proxy.service_account = {
      service_account_id = "3b63d997-a7c8-4315-a2f4-d9b5792f79d9";
      service_account_secret = service_account_secret;
    };
    frontend = {
      app_handler.insecure = false;
      archiver.insecure = false;
      service_account = {
        service_account_id = "3b63d997-a7c8-4315-a2f4-d9b5792f79d9";
        service_account_secret = service_account_secret;
      };
    };
    auth_basic.auth_providers.ldap.bind_password = reva_password;
    auth_bearer.auth_providers.oidc.insecure = false;
    users.drivers.ldap.bind_password = reva_password;
    groups.drivers.ldap.bind_password = reva_password;
    ocdav.insecure = false;
    thumbnails.thumbnail = {
      transfer_secret = ph."ocis/thumbnails_transfer_secret";
      webdav_allow_insecure = false;
      cs3_allow_insecure = false;
    };
    search = {
      events.tls_insecure = false;
      service_account = {
        service_account_id = "3b63d997-a7c8-4315-a2f4-d9b5792f79d9";
        service_account_secret = service_account_secret;
      };
    };
    settings.service_account_ids = [ "3b63d997-a7c8-4315-a2f4-d9b5792f79d9" ];
    sharing.events.tls_insecure = false;
    storage_users = {
      events.tls_insecure = false;
      mount_id = "f67f6b6a-3dba-49c7-a1a8-86704cd9a70e";
      service_account = {
        service_account_id = "3b63d997-a7c8-4315-a2f4-d9b5792f79d9";
        service_account_secret = service_account_secret;
      };
    };
    notifications = {
      notifications.events.tls_insecure = false;
      service_account = {
        service_account_id = "3b63d997-a7c8-4315-a2f4-d9b5792f79d9";
        service_account_secret = service_account_secret;
      };
    };
    nats.nats.tls_skip_verify_client_cert = false;
    gateway.storage_registry.storage_users_mount_id = "f67f6b6a-3dba-49c7-a1a8-86704cd9a70e";
    userlog.service_account = {
      service_account_id = "3b63d997-a7c8-4315-a2f4-d9b5792f79d9";
      service_account_secret = service_account_secret;
    };
    auth_service.service_account = {
      service_account_id = "3b63d997-a7c8-4315-a2f4-d9b5792f79d9";
      service_account_secret = service_account_secret;
    };
    clientlog.service_account = {
      service_account_id = "3b63d997-a7c8-4315-a2f4-d9b5792f79d9";
      service_account_secret = service_account_secret;
    };
  };
}