#!/bin/bash

encrypt() {
    for _file in $(ls ${1}_uncrypted); do
        _output=$(echo ${_file} | awk -F"." '{print $1}').json
        sops -e --input-type binary ${1}_uncrypted/${_file} > ${1}/${_output}
    done
}

encrypt "config/secrets"
encrypt "config/secrets_home"